language: python
python:
#  - "3.2"
#  - "3.3"
  - "3.4"
  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly"
# command to run tests
before_script:
  - git config --global user.email "atester@rtc.to"
  - git config --global user.name "A Tester"

script: python -m unittest discover -s tests